name: yummy
services:
  backend:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    
  db:
    image: postgres
    container_name: yummy_db
    restart: always
    ports:
      - '5432:5432'
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - ./sql/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    env_file:
      - ./db.env
    expose:
      - 5432